name: Build and Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # the Node.js versions to build on
        node-version: [20.x]

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint the project
        run: yarn lint

      - name: Build the project
        run: yarn build
        env:
          CI: true
